
package com.nbdeli.demo.transonlineorder;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "transOnlineOrderActionService", targetNamespace = "transOnlineOrder", wsdlLocation = "http://61.190.39.14/services/transOnlineOrder?wsdl")
public class TransOnlineOrderActionService
        extends Service {

    private final static URL TRANSONLINEORDERACTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSONLINEORDERACTIONSERVICE_EXCEPTION;
    private final static QName TRANSONLINEORDERACTIONSERVICE_QNAME = new QName("transOnlineOrder", "transOnlineOrderActionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://61.190.39.14/services/transOnlineOrder?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSONLINEORDERACTIONSERVICE_WSDL_LOCATION = url;
        TRANSONLINEORDERACTIONSERVICE_EXCEPTION = e;
    }

    public TransOnlineOrderActionService() {
        super(__getWsdlLocation(), TRANSONLINEORDERACTIONSERVICE_QNAME);
    }

    public TransOnlineOrderActionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSONLINEORDERACTIONSERVICE_QNAME, features);
    }

    public TransOnlineOrderActionService(URL wsdlLocation) {
        super(wsdlLocation, TRANSONLINEORDERACTIONSERVICE_QNAME);
    }

    public TransOnlineOrderActionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSONLINEORDERACTIONSERVICE_QNAME, features);
    }

    public TransOnlineOrderActionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransOnlineOrderActionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns TransOnlineOrderAction
     */
    @WebEndpoint(name = "transOnlineOrder")
    public TransOnlineOrderAction getTransOnlineOrder() {
        return super.getPort(new QName("transOnlineOrder", "transOnlineOrder"), TransOnlineOrderAction.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns TransOnlineOrderAction
     */
    @WebEndpoint(name = "transOnlineOrder")
    public TransOnlineOrderAction getTransOnlineOrder(WebServiceFeature... features) {
        return super.getPort(new QName("transOnlineOrder", "transOnlineOrder"), TransOnlineOrderAction.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSONLINEORDERACTIONSERVICE_EXCEPTION != null) {
            throw TRANSONLINEORDERACTIONSERVICE_EXCEPTION;
        }
        return TRANSONLINEORDERACTIONSERVICE_WSDL_LOCATION;
    }

}
