
package com.nbdeli.demo.transonlineorder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "transOnlineOrderAction", targetNamespace = "transOnlineOrder")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransOnlineOrderAction {


    /**
     * 
     * @param str
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "status", targetNamespace = "transOnlineOrder")
    @RequestWrapper(localName = "transOnlineOrder", targetNamespace = "transOnlineOrder", className = "transonlineorder.TransOnlineOrder")
    @ResponseWrapper(localName = "transOnlineOrderResponse", targetNamespace = "transOnlineOrder", className = "transonlineorder.TransOnlineOrderResponse")
    public String transOnlineOrder(
        @WebParam(name = "str", targetNamespace = "transOnlineOrder")
        String str);

}
